import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/header";
import { AuthSessionProvider } from "@/components/providers/session-provider";
import { QueryProvider } from "@/components/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>
        <QueryProvider>
          <AuthSessionProvider>
            <Header />
            {children}
          </AuthSessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
